/** A literal in document units, or a persisted native parameter binding. */
export type GearScalar = number | { readonly parameterId: string };

/** Unshifted external involute gear. Backlash is the tooth thinning of this gear. */
export interface SpurGearInputs {
  readonly teeth: GearScalar;
  readonly module: GearScalar;
  readonly faceWidth: GearScalar;
  readonly pressureAngleDegrees?: GearScalar;
  readonly boreDiameter?: GearScalar;
  readonly backlash?: GearScalar;
  /** Maximum involute approximation error in document units; defaults to max(module / 400, 0.0000008). */
  readonly profileTolerance?: GearScalar;
}

export interface SpurGearValues {
  readonly teeth: number;
  readonly module: number;
  readonly faceWidth: number;
  readonly pressureAngleDegrees: number;
  readonly boreDiameter: number;
  readonly backlash: number;
  readonly profileTolerance: number;
}

/** Native authored recipe; its ordinary sketch entities are regenerated by cad-core. */
export interface SpurGearSource {
  readonly kind: "spurGear";
  readonly featureId: string;
  readonly inputs: SpurGearInputs;
  readonly values: SpurGearValues;
}

export interface FeatureSpurGearOp extends SpurGearInputs {
  readonly op: "feature.spurGear";
  readonly id: string;
  readonly bodyId: string;
  readonly sketchId: string;
  readonly name?: string;
  readonly plane?: "XY" | "XZ" | "YZ";
}

export interface FeatureUpdateSpurGearOp {
  readonly op: "feature.updateSpurGear";
  readonly id: string;
  readonly name?: string;
  readonly teeth?: GearScalar;
  readonly module?: GearScalar;
  readonly faceWidth?: GearScalar;
  readonly pressureAngleDegrees?: GearScalar;
  readonly boreDiameter?: GearScalar;
  readonly backlash?: GearScalar;
  readonly profileTolerance?: GearScalar;
}

export function isSpurGearInputs(
  value: unknown,
  partial = false
): value is SpurGearInputs {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const v = value as Record<string, unknown>;
  const scalar = (x: unknown) =>
    (typeof x === "number" && Number.isFinite(x)) ||
    (!!x &&
      typeof x === "object" &&
      !Array.isArray(x) &&
      Object.keys(x).length === 1 &&
      typeof (x as { parameterId?: unknown }).parameterId === "string" &&
      (x as { parameterId: string }).parameterId.trim().length > 0);
  return (
    (partial || ["teeth", "module", "faceWidth"].every((k) => k in v)) &&
    [
      "teeth",
      "module",
      "faceWidth",
      "pressureAngleDegrees",
      "boreDiameter",
      "backlash",
      "profileTolerance"
    ].every((k) => v[k] === undefined || scalar(v[k]))
  );
}

export function isSpurGearOp(
  value: unknown
): value is FeatureSpurGearOp | FeatureUpdateSpurGearOp {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const v = value as Record<string, unknown>;
  const create = v.op === "feature.spurGear";
  if (!create && v.op !== "feature.updateSpurGear") return false;
  const allowed = [
    "op",
    "id",
    "name",
    "teeth",
    "module",
    "faceWidth",
    "pressureAngleDegrees",
    "boreDiameter",
    "backlash",
    "profileTolerance",
    ...(create ? ["bodyId", "sketchId", "plane"] : [])
  ];
  const id = (x: unknown) => typeof x === "string" && x.trim().length > 0;
  return (
    Object.keys(v).every((k) => allowed.includes(k)) &&
    id(v.id) &&
    (!create || (id(v.bodyId) && id(v.sketchId))) &&
    (v.name === undefined || id(v.name)) &&
    (v.plane === undefined || ["XY", "XZ", "YZ"].includes(String(v.plane))) &&
    isSpurGearInputs(v, !create) &&
    (create || Object.keys(v).some((k) => k !== "op" && k !== "id"))
  );
}
