import {
  createOcctBoxMesh,
  createOcctCylinderMesh,
  createOcctSphereMesh,
  createOcctConeMesh,
  createOcctTorusMesh,
  createOcctBooleanExtrudeMesh,
  createOcctEdgeFinishMesh,
  createOcctHoleMesh,
  createOcctRevolveProfileMesh,
  createOcctExactBodyMetadata,
  createOcctExactTopologySnapshot,
  createOcctExactTopologyCheckpointPayload,
  createOcctStepImport,
  createOcctStepExport,
  createOcctLinearPatternMesh,
  createOcctCircularPatternMesh,
  createOcctMirrorMesh,
  createOcctShellMesh,
  createOcctSweepMesh
} from "@web-cad/occt-wasm";
import {
  executeGeometryKernelRequestWithMeshFactory,
  getGeometryKernelExactExportCapabilities,
  getGeometryKernelStepImportCapabilities,
  getGeometryResponseTransferables,
  type BooleanExtrudePrimitiveSource,
  type BooleanExtrudeResultSource,
  type BooleanExtrudeSource,
  type BooleanExtrudesRequest,
  type BoxGeometryDimensions,
  type ChamferEdgeFinishRequest,
  type ConeGeometryDimensions,
  type CylinderGeometryDimensions,
  type ExactBodyMetadataRequest,
  type ExactBodyMetadataSource,
  type ExactBooleanExtrudesMetadataSource,
  type ExactEdgeFinishMetadataSource,
  type ExactExtrudeMetadataSource,
  type ExactHoleMetadataSource,
  type ExactTopologySnapshotRequest,
  type ExactTopologyCheckpointPayloadRequest,
  type ExactRevolveMetadataSource,
  type ExactStepExportBodySource,
  type ExactStepExportRequest,
  type GeometryKernelBounds,
  type GeometryKernelBooleanOperation,
  type GeometryKernelDocumentUnit,
  type GeometryKernelError,
  type GeometryKernelErrorCode,
  type GeometryKernelEdgeFinishEdgeRole,
  type GeometryKernelEdgeFinishMeshFactory,
  type GeometryKernelEdgeFinishMeshFactoryInput,
  type GeometryKernelEdgeFinishOperation,
  type GeometryKernelExactExportCapability,
  type GeometryKernelExactExportCapabilityStatus,
  type GeometryKernelExactExportFormat,
  type GeometryKernelExactBodyMetadata,
  type GeometryKernelExactBodyMetadataSuccessResponse,
  type GeometryKernelExactTopologySnapshot,
  type GeometryKernelExactTopologySnapshotFactory,
  type GeometryKernelExactTopologySnapshotSuccessResponse,
  type GeometryKernelExactTopologyCheckpointPayload,
  type GeometryKernelExactTopologyCheckpointPayloadFactory,
  type GeometryKernelExactTopologyCheckpointPayloadSuccessResponse,
  type GeometryKernelExactStepExportArtifact,
  type GeometryKernelExactStepExportFactory,
  type GeometryKernelExactStepExportSuccessResponse,
  type GeometryKernelImportedBodyCheckpointPayload,
  type GeometryKernelImportedBodyPayload,
  type GeometryKernelImportedBodyShapeType,
  type GeometryKernelExactMetadataDiagnostic,
  type GeometryKernelExtrudeSide,
  type GeometryKernelExtrudeProfileKind,
  type GeometryKernelHoleDepthMode,
  type GeometryKernelHoleDirection,
  type GeometryKernelHoleMeshFactory,
  type GeometryKernelMeasurementConfidence,
  type GeometryKernelMeasurementSource,
  type GeometryKernelMeshRequest,
  type GeometryKernelMeshSuccessResponse,
  type GeometryKernelOp,
  type GeometryKernelPrimitive,
  type GeometryKernelRevolveProfileMeshFactory,
  type GeometryKernelResponseForRequest,
  type GeometryKernelSketchPlane,
  type GeometryKernelRequest,
  type GeometryKernelResponse,
  type GeometryKernelStepImportCapability,
  type GeometryKernelStepImportCapabilityInput,
  type GeometryKernelStepImportCapabilityStatus,
  type GeometryKernelStepImportDiagnostic,
  type GeometryKernelStepImportDiagnosticCode,
  type GeometryKernelStepImportDiagnosticSeverity,
  type GeometryKernelStepImportFactory,
  type GeometryKernelStepImportResult,
  type GeometryKernelStepImportSuccessResponse,
  type GeometryKernelSuccessResponse,
  type GeometryKernelTopologyCounts,
  type GeometryKernelTopologyDiagnostic,
  type GeometryKernelTopologyEntityCounts,
  type GeometryKernelTopologyEntityDescriptor,
  type GeometryKernelTopologyEntityKind,
  type GeometryKernelTopologyCheckpointSignatureEntity,
  type GeometryKernelTopologyCheckpointSignaturePayload,
  type GeometryKernelVersion,
  type GeometryKernelErrorResponse,
  type EdgeFinishRequest,
  type ExtrudeGeometryProfile,
  type FilletEdgeFinishRequest,
  type HoleRequest,
  type HoleToolSource,
  type RectangleExtrudeProfile,
  type RevolveGeometryAxis,
  type RevolveGeometryProfile,
  type RevolveProfileRequest,
  type CircleExtrudeProfile,
  type SerializableMeshData,
  type SphereGeometryDimensions,
  type StepImportRequest,
  type TessellateBoxRequest,
  type TessellateConeRequest,
  type TessellateCylinderRequest,
  type TessellateExtrudeRequest,
  type TessellateSphereRequest,
  type TessellateTorusRequest,
  type TorusGeometryDimensions,
  type TessellationOptions,
  type LinearPatternRequest,
  type CircularPatternRequest,
  type PatternSeedSource,
  type GeometryKernelDirection,
  type GeometryKernelAxisFrame,
  type MirrorRequest,
  type MirrorSeedSource,
  type GeometryKernelPlaneFrame,
  type GeometryKernelMirrorMeshFactory,
  type ShellRequest,
  type ShellTargetSource,
  type GeometryKernelShellMeshFactory,
  type SweepRequest,
  type SweepProfileSource,
  type SweepPathSegment,
  type ExactSweepMetadataSource,
  type GeometryKernelSweepMeshFactory
} from "./kernel";

export type {
  BooleanExtrudePrimitiveSource,
  BooleanExtrudeResultSource,
  BooleanExtrudeSource,
  BooleanExtrudesRequest,
  BoxGeometryDimensions,
  ChamferEdgeFinishRequest,
  ConeGeometryDimensions,
  CylinderGeometryDimensions,
  ExactBodyMetadataRequest,
  ExactBodyMetadataSource,
  ExactBooleanExtrudesMetadataSource,
  ExactEdgeFinishMetadataSource,
  ExactExtrudeMetadataSource,
  ExactHoleMetadataSource,
  ExactTopologySnapshotRequest,
  ExactTopologyCheckpointPayloadRequest,
  ExactRevolveMetadataSource,
  ExactStepExportBodySource,
  ExactStepExportRequest,
  GeometryKernelBounds,
  GeometryKernelBooleanOperation,
  GeometryKernelDocumentUnit,
  GeometryKernelError,
  GeometryKernelErrorCode,
  GeometryKernelEdgeFinishEdgeRole,
  GeometryKernelEdgeFinishMeshFactory,
  GeometryKernelEdgeFinishMeshFactoryInput,
  GeometryKernelEdgeFinishOperation,
  GeometryKernelExactExportCapability,
  GeometryKernelExactExportCapabilityStatus,
  GeometryKernelExactExportFormat,
  GeometryKernelExactBodyMetadata,
  GeometryKernelExactBodyMetadataSuccessResponse,
  GeometryKernelExactTopologySnapshot,
  GeometryKernelExactTopologySnapshotFactory,
  GeometryKernelExactTopologySnapshotSuccessResponse,
  GeometryKernelExactTopologyCheckpointPayload,
  GeometryKernelExactTopologyCheckpointPayloadFactory,
  GeometryKernelExactTopologyCheckpointPayloadSuccessResponse,
  GeometryKernelExactStepExportArtifact,
  GeometryKernelExactStepExportFactory,
  GeometryKernelExactStepExportSuccessResponse,
  GeometryKernelImportedBodyCheckpointPayload,
  GeometryKernelImportedBodyPayload,
  GeometryKernelImportedBodyShapeType,
  GeometryKernelExactMetadataDiagnostic,
  GeometryKernelExtrudeSide,
  GeometryKernelExtrudeProfileKind,
  GeometryKernelHoleDepthMode,
  GeometryKernelHoleDirection,
  GeometryKernelHoleMeshFactory,
  GeometryKernelMeasurementConfidence,
  GeometryKernelMeasurementSource,
  GeometryKernelMeshRequest,
  GeometryKernelMeshSuccessResponse,
  GeometryKernelOp,
  GeometryKernelPrimitive,
  GeometryKernelRevolveProfileMeshFactory,
  GeometryKernelResponseForRequest,
  GeometryKernelSketchPlane,
  GeometryKernelRequest,
  GeometryKernelResponse,
  GeometryKernelStepImportCapability,
  GeometryKernelStepImportCapabilityInput,
  GeometryKernelStepImportCapabilityStatus,
  GeometryKernelStepImportDiagnostic,
  GeometryKernelStepImportDiagnosticCode,
  GeometryKernelStepImportDiagnosticSeverity,
  GeometryKernelStepImportFactory,
  GeometryKernelStepImportResult,
  GeometryKernelStepImportSuccessResponse,
  GeometryKernelSuccessResponse,
  GeometryKernelTopologyCounts,
  GeometryKernelTopologyDiagnostic,
  GeometryKernelTopologyEntityCounts,
  GeometryKernelTopologyEntityDescriptor,
  GeometryKernelTopologyEntityKind,
  GeometryKernelTopologyCheckpointSignatureEntity,
  GeometryKernelTopologyCheckpointSignaturePayload,
  GeometryKernelVersion,
  GeometryKernelErrorResponse,
  EdgeFinishRequest,
  ExtrudeGeometryProfile,
  FilletEdgeFinishRequest,
  HoleRequest,
  HoleToolSource,
  RectangleExtrudeProfile,
  RevolveGeometryAxis,
  RevolveGeometryProfile,
  RevolveProfileRequest,
  CircleExtrudeProfile,
  SerializableMeshData,
  SphereGeometryDimensions,
  StepImportRequest,
  TessellateBoxRequest,
  TessellateConeRequest,
  TessellateCylinderRequest,
  TessellateExtrudeRequest,
  TessellateSphereRequest,
  TessellateTorusRequest,
  TorusGeometryDimensions,
  TessellationOptions,
  LinearPatternRequest,
  CircularPatternRequest,
  PatternSeedSource,
  GeometryKernelDirection,
  GeometryKernelAxisFrame,
  MirrorRequest,
  MirrorSeedSource,
  GeometryKernelPlaneFrame,
  GeometryKernelMirrorMeshFactory,
  ShellRequest,
  ShellTargetSource,
  GeometryKernelShellMeshFactory,
  SweepRequest,
  SweepProfileSource,
  SweepPathSegment,
  ExactSweepMetadataSource,
  GeometryKernelSweepMeshFactory
};
export {
  getGeometryKernelExactExportCapabilities,
  getGeometryKernelStepImportCapabilities,
  getGeometryResponseTransferables
};

export async function executeGeometryKernelRequest<
  T extends GeometryKernelRequest
>(request: T): Promise<GeometryKernelResponseForRequest<T>> {
  return executeGeometryKernelRequestWithMeshFactory(
    {
      createBoxMesh: createOcctBoxMesh,
      createCylinderMesh: createOcctCylinderMesh,
      createSphereMesh: createOcctSphereMesh,
      createConeMesh: createOcctConeMesh,
      createTorusMesh: createOcctTorusMesh,
      createBooleanExtrudeMesh: createOcctBooleanExtrudeMesh,
      createEdgeFinishMesh: createOcctEdgeFinishMesh,
      createHoleMesh: createOcctHoleMesh,
      createRevolveProfileMesh: createOcctRevolveProfileMesh,
      createExactBodyMetadata: createOcctExactBodyMetadata,
      createExactTopologySnapshot: createOcctExactTopologySnapshot,
      createExactTopologyCheckpointPayload:
        createOcctExactTopologyCheckpointPayload,
      createStepImport: createOcctStepImport,
      createExactStepExport: createOcctStepExport,
      createLinearPatternMesh: createOcctLinearPatternMesh,
      createCircularPatternMesh: createOcctCircularPatternMesh,
      createMirrorMesh: createOcctMirrorMesh,
      createShellMesh: createOcctShellMesh,
      createSweepMesh: createOcctSweepMesh
    },
    request
  );
}
