import {
  createOcctBoxMesh,
  createOcctCylinderMesh,
  createOcctSphereMesh,
  createOcctConeMesh,
  createOcctTorusMesh,
  createOcctBooleanExtrudeMesh,
  createOcctEdgeFinishMesh,
  createOcctHoleMesh,
  createOcctRevolveProfileMesh,
  createOcctExactBodyMetadata
} from "@web-cad/occt-wasm";
import {
  executeGeometryKernelRequestWithMeshFactory,
  getGeometryResponseTransferables,
  type BooleanExtrudeSource,
  type BooleanExtrudesRequest,
  type BoxGeometryDimensions,
  type ChamferEdgeFinishRequest,
  type ConeGeometryDimensions,
  type CylinderGeometryDimensions,
  type ExactBodyMetadataRequest,
  type ExactBodyMetadataSource,
  type ExactBooleanExtrudesMetadataSource,
  type ExactExtrudeMetadataSource,
  type ExactHoleMetadataSource,
  type ExactRevolveMetadataSource,
  type GeometryKernelBounds,
  type GeometryKernelBooleanOperation,
  type GeometryKernelError,
  type GeometryKernelErrorCode,
  type GeometryKernelEdgeFinishEdgeRole,
  type GeometryKernelEdgeFinishMeshFactory,
  type GeometryKernelEdgeFinishMeshFactoryInput,
  type GeometryKernelEdgeFinishOperation,
  type GeometryKernelExactBodyMetadata,
  type GeometryKernelExactBodyMetadataSuccessResponse,
  type GeometryKernelExactMetadataDiagnostic,
  type GeometryKernelExtrudeSide,
  type GeometryKernelExtrudeProfileKind,
  type GeometryKernelHoleDepthMode,
  type GeometryKernelHoleDirection,
  type GeometryKernelHoleMeshFactory,
  type GeometryKernelMeasurementConfidence,
  type GeometryKernelMeasurementSource,
  type GeometryKernelMeshRequest,
  type GeometryKernelMeshSuccessResponse,
  type GeometryKernelOp,
  type GeometryKernelPrimitive,
  type GeometryKernelRevolveProfileMeshFactory,
  type GeometryKernelResponseForRequest,
  type GeometryKernelSketchPlane,
  type GeometryKernelRequest,
  type GeometryKernelResponse,
  type GeometryKernelSuccessResponse,
  type GeometryKernelTopologyCounts,
  type GeometryKernelVersion,
  type GeometryKernelErrorResponse,
  type EdgeFinishRequest,
  type ExtrudeGeometryProfile,
  type FilletEdgeFinishRequest,
  type HoleRequest,
  type HoleToolSource,
  type RectangleExtrudeProfile,
  type RevolveGeometryAxis,
  type RevolveGeometryProfile,
  type RevolveProfileRequest,
  type CircleExtrudeProfile,
  type SerializableMeshData,
  type SphereGeometryDimensions,
  type TessellateBoxRequest,
  type TessellateConeRequest,
  type TessellateCylinderRequest,
  type TessellateExtrudeRequest,
  type TessellateSphereRequest,
  type TessellateTorusRequest,
  type TorusGeometryDimensions,
  type TessellationOptions
} from "./kernel";

export type {
  BooleanExtrudeSource,
  BooleanExtrudesRequest,
  BoxGeometryDimensions,
  ChamferEdgeFinishRequest,
  ConeGeometryDimensions,
  CylinderGeometryDimensions,
  ExactBodyMetadataRequest,
  ExactBodyMetadataSource,
  ExactBooleanExtrudesMetadataSource,
  ExactExtrudeMetadataSource,
  ExactHoleMetadataSource,
  ExactRevolveMetadataSource,
  GeometryKernelBounds,
  GeometryKernelBooleanOperation,
  GeometryKernelError,
  GeometryKernelErrorCode,
  GeometryKernelEdgeFinishEdgeRole,
  GeometryKernelEdgeFinishMeshFactory,
  GeometryKernelEdgeFinishMeshFactoryInput,
  GeometryKernelEdgeFinishOperation,
  GeometryKernelExactBodyMetadata,
  GeometryKernelExactBodyMetadataSuccessResponse,
  GeometryKernelExactMetadataDiagnostic,
  GeometryKernelExtrudeSide,
  GeometryKernelExtrudeProfileKind,
  GeometryKernelHoleDepthMode,
  GeometryKernelHoleDirection,
  GeometryKernelHoleMeshFactory,
  GeometryKernelMeasurementConfidence,
  GeometryKernelMeasurementSource,
  GeometryKernelMeshRequest,
  GeometryKernelMeshSuccessResponse,
  GeometryKernelOp,
  GeometryKernelPrimitive,
  GeometryKernelRevolveProfileMeshFactory,
  GeometryKernelResponseForRequest,
  GeometryKernelSketchPlane,
  GeometryKernelRequest,
  GeometryKernelResponse,
  GeometryKernelSuccessResponse,
  GeometryKernelTopologyCounts,
  GeometryKernelVersion,
  GeometryKernelErrorResponse,
  EdgeFinishRequest,
  ExtrudeGeometryProfile,
  FilletEdgeFinishRequest,
  HoleRequest,
  HoleToolSource,
  RectangleExtrudeProfile,
  RevolveGeometryAxis,
  RevolveGeometryProfile,
  RevolveProfileRequest,
  CircleExtrudeProfile,
  SerializableMeshData,
  SphereGeometryDimensions,
  TessellateBoxRequest,
  TessellateConeRequest,
  TessellateCylinderRequest,
  TessellateExtrudeRequest,
  TessellateSphereRequest,
  TessellateTorusRequest,
  TorusGeometryDimensions,
  TessellationOptions
};
export { getGeometryResponseTransferables };

export async function executeGeometryKernelRequest<
  T extends GeometryKernelRequest
>(request: T): Promise<GeometryKernelResponseForRequest<T>> {
  return executeGeometryKernelRequestWithMeshFactory(
    {
      createBoxMesh: createOcctBoxMesh,
      createCylinderMesh: createOcctCylinderMesh,
      createSphereMesh: createOcctSphereMesh,
      createConeMesh: createOcctConeMesh,
      createTorusMesh: createOcctTorusMesh,
      createBooleanExtrudeMesh: createOcctBooleanExtrudeMesh,
      createEdgeFinishMesh: createOcctEdgeFinishMesh,
      createHoleMesh: createOcctHoleMesh,
      createRevolveProfileMesh: createOcctRevolveProfileMesh,
      createExactBodyMetadata: createOcctExactBodyMetadata
    },
    request
  );
}
